// @ts-ignore: generated by open-next build
import openNextWorker from './.open-next/worker.js'
// @ts-ignore: re-export durable objects and handlers from OpenNext
export * from './.open-next/worker.js'

import { requestDrizzleMap, wrapResponseWithDbCleanup } from './src/lib/db-lifecycle'

export default {
  async fetch(request: Request, env: any, ctx: any): Promise<Response> {
    let response: Response
    try {
      response = await openNextWorker.fetch(request, env, ctx)
    } catch (error) {
      const cf = (globalThis as any)[Symbol.for('__cloudflare-context__')]
      const scope =
        (cf ? requestDrizzleMap.get(cf) : undefined) ||
        (ctx ? requestDrizzleMap.get(ctx) : undefined)

      if (scope && !scope.ended) {
        scope.ended = true
        const closePromise = scope.pool.end().catch((err: unknown) => {
          console.error('[DB-CLEANUP-ERROR]:', err)
        })
        if (typeof ctx?.waitUntil === 'function') {
          ctx.waitUntil(closePromise)
        }
      }
      throw error
    }

    const cf = (globalThis as any)[Symbol.for('__cloudflare-context__')]
    const scope =
      (cf ? requestDrizzleMap.get(cf) : undefined) ||
      (ctx ? requestDrizzleMap.get(ctx) : undefined)

    return wrapResponseWithDbCleanup(response, ctx, scope)
  },
}
