/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    leads: Lead;
    invoices: Invoice;
    poles: Pole;
    services: Service;
    'case-studies': CaseStudy;
    posts: Post;
    pages: Page;
    media: Media;
    users: User;
    'access-requests': AccessRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    poles: {
      leads: 'leads';
      services: 'services';
    };
  };
  collectionsSelect: {
    leads: LeadsSelect<false> | LeadsSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    poles: PolesSelect<false> | PolesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'access-requests': AccessRequestsSelect<false> | AccessRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Dossiers prospects, demandes de devis et opportunités commerciales entrantes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  /**
   * Prénom soumis par le prospect (strictement immuable).
   */
  firstname: string;
  /**
   * Nom de famille soumis par le prospect (strictement immuable).
   */
  lastname: string;
  /**
   * Organisation / Entreprise renseignée par le prospect (immuable).
   */
  company?: string | null;
  /**
   * Adresse e-mail originale fournie par le prospect (strictement immuable).
   */
  email: string;
  /**
   * Numéro de contact renseigné par le prospect (immuable).
   */
  phone?: string | null;
  /**
   * Type de demande original choisi par le prospect (immuable).
   */
  requestType: 'devis' | 'cadrage' | 'partenariat' | 'autre';
  /**
   * Pôle d'expertise ciblé par le prospect lors de la soumission (immuable).
   */
  pole?: (number | null) | Pole;
  /**
   * Message original transmis par le prospect (strictement immuable).
   */
  message: string;
  /**
   * Origine technique de la demande (immuable).
   */
  source?: string | null;
  status: 'new' | 'contacted' | 'qualified' | 'converted' | 'archived';
  /**
   * Urgence opérationnelle du prospect.
   */
  priority?: ('low' | 'medium' | 'high' | 'urgent') | null;
  /**
   * Membre de l'équipe en charge du traitement commercial.
   */
  assignedTo?: (number | null) | User;
  /**
   * Historique des échanges, qualifications et actions menées (interne Bokengi, strictement confidentiel).
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pôles d'expertise métier constitutifs du Groupe Bokengi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poles".
 */
export interface Pole {
  id: number;
  name: string;
  /**
   * Identifiant unique pour l'URL (ex: it, digital, business, consulting, events).
   */
  slug: string;
  /**
   * Présentation concise utilisée sur la page d'accueil et les cartes d'aperçu.
   */
  shortDescription?: string | null;
  /**
   * Présentation complète des missions, de la vision et de la proposition de valeur du pôle.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Code de l'icône SVG (ex: server, code, trending-up, compass, calendar).
   */
  icon?: string | null;
  order?: number | null;
  status: 'draft' | 'published';
  seo?: {
    /**
     * Titre spécifique pour les moteurs de recherche (laisser vide pour utiliser le titre par défaut).
     */
    title?: string | null;
    /**
     * Description pour les moteurs de recherche et les partages sociaux (150-160 caractères recommandés).
     */
    description?: string | null;
    /**
     * Image au format 1200x630px recommandée pour les aperçus sociaux.
     */
    image?: (number | null) | Media;
  };
  /**
   * Ensemble des sollicitations commerciales et techniques transmises pour ce pôle.
   */
  leads?: {
    docs?: (number | Lead)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Offres et prestations rattachées à ce pôle d'expertise.
   */
  services?: {
    docs?: (number | Service)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Centralisation des ressources visuelles, photographies et documents du Groupe Bokengi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Services et offres commerciales commercialisés par les pôles Bokengi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Slug URL (ex: audit-securite-pentest).
   */
  slug: string;
  /**
   * Sélectionnez le pôle auquel ce service est affilié.
   */
  pole: number | Pole;
  category?: string | null;
  /**
   * Résumé synthétique pour les grilles et listes de services.
   */
  shortDescription?: string | null;
  /**
   * Description détaillée de la prestation, méthodologie et livrables attendus.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  technicalTags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  order?: number | null;
  status: 'draft' | 'published';
  seo?: {
    /**
     * Titre spécifique pour les moteurs de recherche (laisser vide pour utiliser le titre par défaut).
     */
    title?: string | null;
    /**
     * Description pour les moteurs de recherche et les partages sociaux (150-160 caractères recommandés).
     */
    description?: string | null;
    /**
     * Image au format 1200x630px recommandée pour les aperçus sociaux.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestion des comptes collaborateurs et attributions des habilitations RBAC.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Rôle d’habilitation système. Le rôle Super Administrateur est réservé exclusivement au compte sanctuarisé ID 1.
   */
  role: 'admin' | 'editor' | 'super-admin';
  /**
   * État d’activation du compte. Seuls les comptes "Actif" peuvent se connecter.
   */
  status: 'active' | 'pending' | 'suspended' | 'rejected';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Module officiel de facturation, devis et gestion comptable Bokengi Group.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  /**
   * Numéro légal généré automatiquement (format BOK-AAAA-XXXX).
   */
  invoiceNumber: string;
  type: 'invoice' | 'quote' | 'credit_note';
  status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
  /**
   * Calculé automatiquement à partir des lignes.
   */
  subtotalHT?: number | null;
  /**
   * Montant de taxe calculé automatiquement.
   */
  totalVAT?: number | null;
  /**
   * Montant total toutes taxes comprises.
   */
  totalTTC?: number | null;
  /**
   * Lier cette pièce à un prospect CRM pour pré-remplir les données client.
   */
  lead?: (number | null) | Lead;
  clientName: string;
  clientCompany?: string | null;
  clientEmail?: string | null;
  clientPhone?: string | null;
  clientAddress?: string | null;
  clientVatNumber?: string | null;
  issueDate: string;
  dueDate: string;
  paymentMethod?: ('virement' | 'carte' | 'cheque' | 'autre') | null;
  items: {
    description: string;
    quantity: number;
    unitPriceHT: number;
    vatRate: number;
    totalHT?: number | null;
    totalTTC?: number | null;
    id?: string | null;
  }[];
  /**
   * Mentions contractuelles et légales imprimées en bas de facture.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Études de cas, retours d'expérience et projets d'envergure menés par Bokengi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  /**
   * Slug URL (ex: esiika, portail-kongama, fleetguard).
   */
  slug: string;
  clientName?: string | null;
  category?: string | null;
  /**
   * Synthèse concise pour les cartes de présentation et les pages listes.
   */
  summary?: string | null;
  /**
   * Environnement du projet, contraintes de départ et attentes initiales.
   */
  context?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Obstacles critiques résolus (scalabilité, latence, cybersécurité, intégration legacy).
   */
  challenge?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Architecture, choix d'ingénierie et méthodologie mise en œuvre.
   */
  solution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Gains qualitatifs et quantitatifs (performances, adoption, sécurité, rentabilité).
   */
  results?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  technologies?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Détails des flux de données, micro-services, sécurité réseau et infrastructure.
   */
  architecture?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  screenshots?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  status: 'draft' | 'published';
  publishedDate?: string | null;
  seo?: {
    /**
     * Titre spécifique pour les moteurs de recherche (laisser vide pour utiliser le titre par défaut).
     */
    title?: string | null;
    /**
     * Description pour les moteurs de recherche et les partages sociaux (150-160 caractères recommandés).
     */
    description?: string | null;
    /**
     * Image au format 1200x630px recommandée pour les aperçus sociaux.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Réservoir éditorial pour les futures actualités sectorielles et articles de fond.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Slug URL de l'article.
   */
  slug: string;
  /**
   * Bref aperçu affiché dans les flux RSS et les cartes d'articles.
   */
  excerpt?: string | null;
  /**
   * Contenu éditorial complet rédigé avec l'éditeur Lexical.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (number | null) | User;
  coverImage?: (number | null) | Media;
  categories?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  status: 'draft' | 'published';
  seo?: {
    /**
     * Titre spécifique pour les moteurs de recherche (laisser vide pour utiliser le titre par défaut).
     */
    title?: string | null;
    /**
     * Description pour les moteurs de recherche et les partages sociaux (150-160 caractères recommandés).
     */
    description?: string | null;
    /**
     * Image au format 1200x630px recommandée pour les aperçus sociaux.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Réservoir éditorial pour les pages institutionnelles sur-mesure et futures extensions de contenu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Slug URL (ex: groupe, legal, confidentialite).
   */
  slug: string;
  /**
   * Corps de texte structuré de la page institutionnelle.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status: 'draft' | 'published';
  seo?: {
    /**
     * Titre spécifique pour les moteurs de recherche (laisser vide pour utiliser le titre par défaut).
     */
    title?: string | null;
    /**
     * Description pour les moteurs de recherche et les partages sociaux (150-160 caractères recommandés).
     */
    description?: string | null;
    /**
     * Image au format 1200x630px recommandée pour les aperçus sociaux.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Demandes d'accès et habilitations en attente d'approbation Super Admin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-requests".
 */
export interface AccessRequest {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  /**
   * Préférence consultative exprimée par le demandeur.
   */
  requestedRole: 'editor' | 'admin';
  justification: string;
  /**
   * Statut du cycle de vie de la demande.
   */
  status: 'pending' | 'approved' | 'rejected' | 'expired';
  /**
   * Rôle formellement attribué lors de l'approbation par le Super Administrateur.
   */
  assignedRole?: ('editor' | 'admin') | null;
  adminNotes?: string | null;
  processedAt?: string | null;
  processedBy?: (number | null) | User;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'poles';
        value: number | Pole;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'access-requests';
        value: number | AccessRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  firstname?: T;
  lastname?: T;
  company?: T;
  email?: T;
  phone?: T;
  requestType?: T;
  pole?: T;
  message?: T;
  source?: T;
  status?: T;
  priority?: T;
  assignedTo?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  invoiceNumber?: T;
  type?: T;
  status?: T;
  subtotalHT?: T;
  totalVAT?: T;
  totalTTC?: T;
  lead?: T;
  clientName?: T;
  clientCompany?: T;
  clientEmail?: T;
  clientPhone?: T;
  clientAddress?: T;
  clientVatNumber?: T;
  issueDate?: T;
  dueDate?: T;
  paymentMethod?: T;
  items?:
    | T
    | {
        description?: T;
        quantity?: T;
        unitPriceHT?: T;
        vatRate?: T;
        totalHT?: T;
        totalTTC?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poles_select".
 */
export interface PolesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  icon?: T;
  order?: T;
  status?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  leads?: T;
  services?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pole?: T;
  category?: T;
  shortDescription?: T;
  content?: T;
  technicalTags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featured?: T;
  order?: T;
  status?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  clientName?: T;
  category?: T;
  summary?: T;
  context?: T;
  challenge?: T;
  solution?: T;
  results?: T;
  technologies?:
    | T
    | {
        name?: T;
        id?: T;
      };
  architecture?: T;
  screenshots?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  featured?: T;
  status?: T;
  publishedDate?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  author?: T;
  coverImage?: T;
  categories?:
    | T
    | {
        name?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  publishedAt?: T;
  status?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  status?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-requests_select".
 */
export interface AccessRequestsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  requestedRole?: T;
  justification?: T;
  status?: T;
  assignedRole?: T;
  adminNotes?: T;
  processedAt?: T;
  processedBy?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Identité corporative, coordonnées officielles, mentions légales et paramètres de facturation.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  /**
   * Ex: SAS, SARL, SA...
   */
  legalForm?: string | null;
  capital?: string | null;
  rcs?: string | null;
  siren?: string | null;
  siret?: string | null;
  vatNumber?: string | null;
  /**
   * L'adresse officielle cible est contact@bokengi-group.com (injectable également via CONTACT_EMAIL).
   */
  contactEmail?: string | null;
  phone?: string | null;
  bankDetails?: {
    bankName?: string | null;
    iban?: string | null;
    bic?: string | null;
  };
  address?: {
    street?: string | null;
    city?: string | null;
    country?: string | null;
  };
  socialLinks?:
    | {
        platform: 'linkedin' | 'twitter' | 'github' | 'youtube' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  domains?: {
    /**
     * URL canonique finale lors de la bascule DNS.
     */
    production?: string | null;
    /**
     * Environnement technique de prévisualisation.
     */
    preview?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Liens du menu principal et bouton d'appel à l'action.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navigation?:
    | {
        label: string;
        url: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    url?: string | null;
    enabled?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Colonnes de navigation, mentions légales et droits réservés de bas de page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  legalForm?: T;
  capital?: T;
  rcs?: T;
  siren?: T;
  siret?: T;
  vatNumber?: T;
  contactEmail?: T;
  phone?: T;
  bankDetails?:
    | T
    | {
        bankName?: T;
        iban?: T;
        bic?: T;
      };
  address?:
    | T
    | {
        street?: T;
        city?: T;
        country?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  domains?:
    | T
    | {
        production?: T;
        preview?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navigation?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        url?: T;
        enabled?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}